#ifndef PRETTY_SER_VERSION_H
#define PRETTY_SER_VERSION_H

#define PRETTY_SER_VERSION_MAJOR    1
#define PRETTY_SER_VERSION_MINOR    0
#define PRETTY_SER_VERSION_REV      4

#endif /* PRETTY_SER_VERSION_H */
